# Generated by Django 4.2.4 on 2024-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='itemQyt',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
