# Generated by Django 4.2.4 on 2023-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
