# Generated by Django 4.2.4 on 2023-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_price',
            field=models.IntegerField(default=500),
        ),
    ]
